# Utilise l'image alpine comme base
FROM alpine:latest

# Installe SQLite
RUN apk add --no-cache sqlite

# Crée un dossier pour stocker la base de données
RUN mkdir -p /data

# Définir le dossier par défaut pour SQLite
WORKDIR /data

# Commande par défaut : lancer SQLite
CMD ["sqlite3"]
